server:
  port: 8080
  context-path: /

#    change if necessary
frontend-server-url: http://localhost:3000

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver

#    change if necessary
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/task_tracker?useSSL=false

  mail:
    host: smtp.gmail.com
    port: 587

    #    change if necessary
    username: ivan96bsu@gmail.com
    password: Sum41forever

    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
